// Code generated by "stringer -type VaultStatus -trimprefix VaultStatus"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VaultStatusLocking-0]
	_ = x[VaultStatusReleased-1]
}

const _VaultStatus_name = "LockingReleased"

var _VaultStatus_index = [...]uint8{0, 7, 15}

func (i VaultStatus) String() string {
	if i < 0 || i >= VaultStatus(len(_VaultStatus_index)-1) {
		return "VaultStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VaultStatus_name[_VaultStatus_index[i]:_VaultStatus_index[i+1]]
}
