// Code generated by "stringer -type VaultType -trimprefix VaultType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VaultTypeNormal-0]
	_ = x[VaultTypeStrict-1]
}

const _VaultType_name = "NormalStrict"

var _VaultType_index = [...]uint8{0, 6, 12}

func (i VaultType) String() string {
	if i < 0 || i >= VaultType(len(_VaultType_index)-1) {
		return "VaultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VaultType_name[_VaultType_index[i]:_VaultType_index[i+1]]
}
