// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fox-one/holder/cmd/holder-server/config"
	"github.com/fox-one/holder/handler/api"
	"github.com/fox-one/holder/handler/rpc"
	"github.com/fox-one/holder/notifier"
	"github.com/fox-one/holder/server"
	"github.com/fox-one/holder/service/asset"
	user2 "github.com/fox-one/holder/service/user"
	"github.com/fox-one/holder/service/wallet"
	"github.com/fox-one/holder/session"
	"github.com/fox-one/holder/store/message"
	"github.com/fox-one/holder/store/pool"
	"github.com/fox-one/holder/store/transaction"
	"github.com/fox-one/holder/store/user"
	"github.com/fox-one/holder/store/vault"
)

// Injectors from wire.go:

func buildServer(cfg *config.Config) (*server.Server, error) {
	db, err := provideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userStore := user.New(db)
	client, err := provideMixinClient(cfg)
	if err != nil {
		return nil, err
	}
	userConfig := provideUserServiceConfig(cfg)
	userService := user2.New(client, userConfig)
	sessionConfig := provideSessionConfig(cfg)
	coreSession := session.New(userStore, userService, sessionConfig)
	poolStore := pool.New(db)
	vaultStore := vault.New(db)
	transactionStore := transaction.New(db)
	walletConfig := provideWalletServiceConfig(cfg)
	walletService := wallet.New(client, walletConfig)
	system := provideSystem(cfg)
	assetService := asset.New(client)
	messageStore := message.New(db)
	localizer, err := provideLocalizer(cfg)
	if err != nil {
		return nil, err
	}
	notifierConfig := _wireConfigValue
	coreNotifier := notifier.New(system, assetService, messageStore, poolStore, vaultStore, userStore, walletService, localizer, notifierConfig)
	apiServer := api.New(coreSession, userService, poolStore, vaultStore, transactionStore, walletService, coreNotifier, system)
	rpcServer := rpc.New(poolStore, vaultStore, transactionStore)
	mux := provideRoute(apiServer, rpcServer, coreSession)
	serverServer := provideServer(mux)
	return serverServer, nil
}

var (
	_wireConfigValue = notifier.Config{}
)
