basePath: /api
definitions:
  actions.CreateRequest:
    properties:
      amount:
        description: payment amount (optional)
        type: number
      asset_id:
        description: payment asset id (optional)
        format: uuid
        type: string
      follow_id:
        description: follow id to track tx (uuid)
        format: uuid
        type: string
      parameters:
        description: |-
          tx parameters
          lock ["bit","8","int","120","int","120"]
          unlock ["bit","9","uuid","{vault_id}"]
          donate ["bit","6"]
        items:
          type: string
        type: array
    type: object
  actions.CreateResponse:
    properties:
      code:
        description: multisig payment code
        type: string
      code_url:
        description: multisig payment code url
        type: string
      memo:
        description: payment memo
        type: string
    type: object
  api.Pagination:
    properties:
      has_next:
        type: boolean
      next_cursor:
        type: string
    type: object
  api.Pool:
    properties:
      amount:
        type: string
      id:
        type: string
      liquidity:
        type: string
      logo:
        type: string
      name:
        type: string
      pardoned_at:
        description: '@inject_tag: swaggertype:"string" format:"date"'
        format: date
        type: string
      price:
        type: string
      profit:
        type: string
      reward:
        type: string
      reward_at:
        description: '@inject_tag: swaggertype:"string" format:"date"'
        format: date
        type: string
      share:
        type: string
    type: object
  api.Resp_ListPools:
    properties:
      pools:
        items:
          $ref: '#/definitions/api.Pool'
        type: array
    type: object
  api.Resp_ListTransactions:
    properties:
      pagination:
        $ref: '#/definitions/api.Pagination'
      transactions:
        items:
          $ref: '#/definitions/api.Transaction'
        type: array
    type: object
  api.Resp_ListVaults:
    properties:
      vaults:
        items:
          $ref: '#/definitions/api.Vault'
        type: array
    type: object
  api.Transaction:
    properties:
      action:
        type: integer
      amount:
        type: string
      asset_id:
        type: string
      created_at:
        description: '@inject_tag: swaggertype:"string" format:"date"'
        format: date
        type: string
      id:
        type: string
      msg:
        type: string
      parameters:
        type: string
      status:
        type: integer
    type: object
  api.Vault:
    properties:
      amount:
        type: string
      asset_id:
        type: string
      created_at:
        description: '@inject_tag: swaggertype:"string" format:"date"'
        format: date
        type: string
      duration:
        type: integer
      id:
        type: string
      liquidity:
        type: string
      locked_price:
        type: string
      min_duration:
        type: integer
      penalty:
        type: string
      pool:
        $ref: '#/definitions/api.Pool'
      released_at:
        description: '@inject_tag: swaggertype:"string" format:"date"'
        format: date
        type: string
      released_price:
        type: string
      reward:
        type: string
      share:
        type: string
      status:
        type: integer
      user_id:
        type: string
    type: object
  system.InfoResponse:
    properties:
      members:
        description: multisig members
        items:
          type: string
        type: array
      oauth_client_id:
        description: oauth client id
        format: uuid
        type: string
      public_key:
        type: string
      threshold:
        description: multisig threshold
        type: integer
    type: object
  system.TimeResponse:
    properties:
      epoch:
        type: integer
      iso:
        type: string
    type: object
  user.LoginRequest:
    properties:
      code:
        description: mixin oauth code
        type: string
    type: object
  user.LoginResponse:
    properties:
      avatar:
        description: user avatar
        type: string
      id:
        description: user mixin id
        format: uuid
        type: string
      language:
        description: Preferred language
        type: string
      name:
        description: user name
        type: string
      scope:
        description: mixin oauth scope
        type: string
      token:
        description: mixin oauth token
        type: string
    type: object
host: holder-api.fox.one
info:
  contact:
    email: support@pando.im
    name: API Support
    url: http://www.pando.im/support
  description: Holder Api Doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://pando.im/terms/
  title: Holder API
  version: "1.0"
paths:
  /actions:
    post:
      consumes:
      - application/json
      parameters:
      - description: request payments
        in: body
        name: request
        schema:
          $ref: '#/definitions/actions.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/actions.CreateResponse'
      summary: request payment code
      tags:
      - actions
  /info:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/system.InfoResponse'
      summary: Show system info
      tags:
      - system
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: request login
        in: body
        name: request
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
      summary: login with mixin oauth code
      tags:
      - user
  /pools:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Resp_ListPools'
      summary: list all pools
      tags:
      - Pools
  /time:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/system.TimeResponse'
      summary: Show server time
      tags:
      - system
  /transactions:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: cursor
        type: string
      - in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Resp_ListTransactions'
      summary: list transactions
      tags:
      - Transactions
  /transactions/{follow_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 'Example: Bearer foo'
        in: header
        name: Authorization
        required: true
        type: string
      - description: follow id
        in: path
        name: follow_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Transaction'
      summary: find tx by follow id
      tags:
      - Transactions
  /vaults:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Resp_ListVaults'
      summary: List Vaults
      tags:
      - Vaults
  /vaults/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: vault id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Vault'
      summary: Find Vault By ID
      tags:
      - Vaults
schemes:
- https
- http
swagger: "2.0"
